version: "3"

services:
  integracaodb:
    build: db
    container_name: integracao-db
    volumes:
      - integracao-volume:/var/lib/postgresql/data
    env_file:
      - db/.env
    ports:
      - "5432:5432"
  integracaoapp:
    image: gleytonlima/gds-ephem-integracao
    container_name: integracao-app
    env_file:
      - app/.env
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: vbeapi.online
      LETSENCRYPT_HOST: vbeapi.online
      LETSENCRYPT_EMAIL: gleytonclima@gmail.com

volumes:
  integracao-volume:

networks:
  default:
    external:
      name: proxy
